### ISSUE TITLE
ImportError: cannot import name 'tf' from 'keras.backend'

### ISSUE THREAD

**Issue by alexst07** [divamgupta/image-segmentation-keras#120]
I am having problems to execute the pre-trained models:

```
import keras_segmentation

model = keras_segmentation.pretrained.pspnet_50_ADE_20K() 
out = model.predict_segmentation(
    inp="input_image.jpg",
    out_fname="out.png"
)
```

```
ImportError                               Traceback (most recent call last)
<ipython-input-22-1a69a6bbd448> in <module>
      1 print(keras.__version__)
----> 2 model = keras_segmentation.pretrained.pspnet_50_ADE_20K()

~/anaconda3/lib/python3.7/site-packages/keras_segmentation/pretrained.py in pspnet_50_ADE_20K()
     44     latest_weights =  keras.utils.get_file( "pspnet50_ade20k.h5" , model_url  )
     45 
---> 46     return model_from_checkpoint_path( model_config , latest_weights  )
     47 
     48 

~/anaconda3/lib/python3.7/site-packages/keras_segmentation/pretrained.py in model_from_checkpoint_path(model_config, latest_weights)
      7 def model_from_checkpoint_path( model_config , latest_weights  ):
      8 
----> 9         model = model_from_name[ model_config['model_class']  ]( model_config['n_classes'] , input_height=model_config['input_height'] , input_width=model_config['input_width'] )
     10         model.load_weights(latest_weights)
     11         return model

~/anaconda3/lib/python3.7/site-packages/keras_segmentation/models/pspnet.py in pspnet_50(n_classes, input_height, input_width)
    103 
    104 def pspnet_50( n_classes ,  input_height=473, input_width=473 ):
--> 105     from ._pspnet_2 import _build_pspnet
    106 
    107     nb_classes = n_classes

~/anaconda3/lib/python3.7/site-packages/keras_segmentation/models/_pspnet_2.py in <module>
     10 from keras.optimizers import SGD
     11 
---> 12 from keras.backend import tf as ktf
     13 import tensorflow as tf
     14 

ImportError: cannot import name 'tf' from 'keras.backend' (/home/alex/anaconda3/lib/python3.7/site-packages/keras/backend/__init__.py)
```

**Comment by divamgupta** [comment]
Which keras version are you using. It should work fine with keras 2.0.0

**Comment by alexst07** [comment]
keras version: 2.3.0

**Comment by sainatarajan** [comment]
If anyone else is having this issue, just install via pip using this command: `pip install git+https://github.com/divamgupta/image-segmentation-keras.git`

**Comment by aviaisr** [comment]
I'm still getting this issue.
I'm working with Keras 2.2.5 and the latest master (06/01/2020).

**Comment by davidADSP** [comment]
Works with 
```
tensorflow==2.0.0
keras==2.3.1
```
