### ISSUE TITLE
Checkpoint is not found

### ISSUE THREAD

**Issue by Caioww** [divamgupta/image-segmentation-keras#237]
I am trying to run this command after I have trained the network but it is giving an error.

```
python -m keras_segmentation predict \
 --checkpoints_path="path_to_checkpoints" \
 --input_path="dataset1/images_prepped_test/" \
 --output_path="path_to_predictions"
```

` File "C:\Users\Caiow\AppData\Local\Programs\Python\Python38\lib\site-packages\keras_segmentation\predict.py", line 175, in predict_multiple
    model = model_from_checkpoint_path(checkpoints_path)
  File "C:\Users\Caiow\AppData\Local\Programs\Python\Python38\lib\site-packages\keras_segmentation\predict.py", line 29, in model_from_checkpoint_path
    assert (latest_weights is not None), "Checkpoint not found."
AssertionError: Checkpoint not found.
`

**Comment by rosegit-lab** [comment]
I have a similar issue. What is your saving weights format?

For my case, it saves as **w.1.index** instead of **w.1**.

**Comment by Caioww** [comment]
> I have a similar issue. What is your saving weights format?
> 
> For my case, it saves as **w.1.index** instead of **w.1**.

I am save as vgg_unet_1.1.index

**Comment by rosegit-lab** [comment]
The problem is coming from the weight extension, I think. Weight extension should be a number so that it is able to find the latest checkpoint while prediction.
I run this two months ago, everything was working well without any problem, but I think, after some update, somehow the saving format of the weights is corrupted. @divamgupta

**Comment by divamgupta** [comment]
Yes, this change is caused by newer versions of tf/keras. Downgrading should work. I will also push the update shortly

**Comment by Caioww** [comment]
> Yes, this change is caused by newer versions of tf/keras. Downgrading should work. I will also push the update shortly

I am using tensorflow version 2.2.0 , i can't downgrade using pip.

**Comment by rosegit-lab** [comment]
@Caioww you can try "**pip install tensorflow==1.4**" ( or any version you want)

**Comment by Caioww** [comment]
> @Caioww you can try "**pip install tensorflow==1.4**" ( or any version you want)

ERROR: Could not find a version that satisfies the requirement tensorflow==1.4 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0)
ERROR: No matching distribution found for tensorflow==1.4

**Comment by yl305237731** [comment]
I also encountered this problem when I used tf2.2.0，if i use tf1.15.0, meeting:  ImportError: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install tensorflow`

**Comment by divamgupta** [comment]
Hi, this have been fixed now. 
You can uninstall the existing keras_segmentation and install the master branch using : `pip install git+https://github.com/divamgupta/image-segmentation-keras
`
That should solve the error.

**Comment by rosegit-lab** [comment]
It is working now, thank you!

**Comment by rosegit-lab** [comment]
Hi again @divamgupta,

I supposed that after your fixing, the problem is solved, but it didn't. It is because, after Keras update, two different files are generated (the weights' file is corrupted), the file which ending with '.index' is the wrong file, its size is so small that it not possible to be saved weights. So, even if the code seems like running without error, indeed it does not work.

**Comment by divamgupta** [comment]
Thanks, I am looking into the issue.

**Comment by divamgupta** [comment]
Something major did change after the keras update. The sample model with sample dataset gives very good accuracy with older keras/tf versions. But with the new versions the training accuracy is also very bad.

**Comment by rosegit-lab** [comment]
Which version of Keras and Tensorflow is working?

**Comment by divamgupta** [comment]
It works perfectly with  TF 1.14.0 and keras 2.1.4

**Comment by divamgupta** [comment]
Its fixed now. Everything should work with latest TF/keras versions.
Here is a working google colab example: https://colab.research.google.com/drive/1Kpy4QGFZ2ZHm69mPfkmLSUes8kj6Bjyi?usp=sharing

**Comment by wassi12** [comment]
> C'est réparé maintenant. Tout devrait fonctionner avec les dernières versions de TF/keras.
> Voici un exemple fonctionnel de google colab : https://colab.research.google.com/drive/1Kpy4QGFZ2ZHm69mPfkmLSUes8kj6Bjyi?usp=sharing

Bonjour Mr @divamgupta . Le lien mentionné ci-dessus marchait parfaitement auparavant. mais à présent , il donne l'erreur : 
AttributeError: module 'keras.utils' has no attribute 'get_file'.
Toute mes tentations pour solutionner cela n'ont pas marché.
Veuillez m’éclairer svp sur comment trouver la solution.
NB: Sur colab il est installé TF et keras :2.5.0
J'ai tenté aussi d'autres combinaison qui n'ont rien donné.
Je serai très ravi de votre réponse prompte face à cette situation.

**Comment by wassi12** [comment]
> Its fixed now. Everything should work with latest TF/keras versions.
> Here is a working google colab example: https://colab.research.google.com/drive/1Kpy4QGFZ2ZHm69mPfkmLSUes8kj6Bjyi?usp=sharing


Hi Mr @divamgupta . The above mentioned link was working perfectly earlier. but now, it gives the error :
AttributeError: module 'keras.utils' has no attribute 'get_file'.
All my attempts to solve this did not work.
Please enlighten me on how to find the solution.
NB: On colab it is installed TF and keras :2.5.0
I have also tried other combinations that have not worked.
I will be very pleased with your prompt response to this situation.

**Comment by Ankit-Vohra** [comment]
@wassi12 were you able to solve the problem? Even I'm stuck on the same issue
It would be really helpful if @divamgupta you could share a solution for this

**Comment by eyildiz-ugoe** [comment]
> Its fixed now. Everything should work with latest TF/keras versions. Here is a working google colab example: https://colab.research.google.com/drive/1Kpy4QGFZ2ZHm69mPfkmLSUes8kj6Bjyi?usp=sharing

Not working with Tensorflow 2.9.0

**Comment by GruMinion** [comment]
Similar error to me as of today

**Comment by hayatkhan8660-maker** [comment]
Traceback (most recent call last):
  File "test.py", line 46, in <module>
    out_dir="F:/Hayat Data/Hayat master's PC backup/drive volume G/image-segmentation-keras-master/fire_segmentation/shufflenet_unet_results/shufflenet_unet11/"
  File "F:\Hayat Data\Hayat master's PC backup\drive volume G\image-segmentation-keras-master\fire_segmentation\keras_segmentation\predict.py", line 194, in predict_multiple
    model = model_from_checkpoint_path(checkpoints_path)
  File "F:\Hayat Data\Hayat master's PC backup\drive volume G\image-segmentation-keras-master\fire_segmentation\keras_segmentation\predict.py", line 29, in model_from_checkpoint_path
    assert (latest_weights is not None), "Checkpoint not found."
AssertionError: Checkpoint not found.

I tried to reinstall keras_segmentation but still its not working..
Any help very be appreciated

**Comment by hayatkhan8660-maker** [comment]
> I am trying to run this command after I have trained the network but it is giving an error.
> 
> ```
> python -m keras_segmentation predict \
>  --checkpoints_path="path_to_checkpoints" \
>  --input_path="dataset1/images_prepped_test/" \
>  --output_path="path_to_predictions"
> ```
> 
> `File "C:\Users\Caiow\AppData\Local\Programs\Python\Python38\lib\site-packages\keras_segmentation\predict.py", line 175, in predict_multiple model = model_from_checkpoint_path(checkpoints_path) File "C:\Users\Caiow\AppData\Local\Programs\Python\Python38\lib\site-packages\keras_segmentation\predict.py", line 29, in model_from_checkpoint_path assert (latest_weights is not None), "Checkpoint not found." AssertionError: Checkpoint not found.`

Have u solved this problem ??

**Comment by hayatkhan8660-maker** [comment]
I solved it :) :)

**Comment by Xenon1997** [comment]
I edited the function find_latest_checkpoint(checkpoints_path, fail_safe=True) and it works:

def find_latest_checkpoint(checkpoints_path, fail_safe=True):

    def get_epoch_number_from_path(path):
        **t_path = path.split("\\")[-1]**
        m_path = t_path.strip(".")
        return m_path
    all_checkpoint_files = glob.glob(checkpoints_path + ".*")
    
    all_checkpoint_files = [ ff.replace(".index" , "") for ff in all_checkpoint_files ]
    # Filter out entries where the epoc_number part is pure number
    all_checkpoint_files = list(filter(lambda f: get_epoch_number_from_path(f)
                                       .isdigit(), all_checkpoint_files))
    print(all_checkpoint_files)
    if not len(all_checkpoint_files):
        # The glob list is empty, don't have a checkpoints_path
        if not fail_safe:
            raise ValueError("Checkpoint path {0} invalid"
                             .format(checkpoints_path))
        else:
            return None

    # Find the checkpoint file with the maximum epoch
    latest_epoch_checkpoint = max(all_checkpoint_files,
                                  key=lambda f:
                                  int(get_epoch_number_from_path(f)))
    return latest_epoch_checkpoint
